const plans = {
  monthly: [
    {
      type: "Starter",
      price: 24,
      ideal: "Ideal for freelancers and contractors just starting out.",
      features: [
        "All Templates",
        "Unlimited Clients & Projects",
        "Invoicing & Payments",
        "Proposal & Contracts",
        "Scheduling",
        "Tasks & Time Tracking",
        "Client CRM",
        "Forms & Questionnaires",
        "Expense Tracking",
        "Up to 5 Project Collaborators",
      ],
    },
    {
      type: "Professional",
      price: 39,
      ideal: "Everything a growing independent business needs to thrive.",
      features: [
        "Everything in Starter, plus:",
        "Custom Branding",
        "Workflow Automations",
        "Client Portal",
        "Unlimited Scheduling events",
        "QuickBooks Integration",
        "Calendly Integration",
        "Zapier Integration",
        "Up to 15 Project Collaborators",
      ],
    },
    {
      type: "Business",
      price: 79,
      ideal: "The perfect package for small businesses and agencies.",
      features: [
        "Everything in Professinal, plus:",
        "Subcontractor Management",
        "Hiring Agreement Templates(1099 contractors)",
        "Subcontractor Onboarding",
        "Talent Pool",
        "3 Team Seats additional seats $9/month",
        "Accountant Access",
        "Connect Multiple Bank Accounts",
        "Unlimited Subcontractors",
        "Unlimited Project Collaborators",
      ],
    },
  ],

  yearly: [
    {
      type: "Starter",
      price: 17,
      ideal: "Ideal for freelancers and contractors just starting out.",
      features: [
        "All Templates",
        "Unlimited Clients & Projects",
        "Invoicing & Payments",
        "Proposal & Contracts",
        "Scheduling",
        "Tasks & Time Tracking",
        "Client CRM",
        "Forms & Questionnaires",
        "Expense Tracking",
        "Up to 5 Project Collaborators",
      ],
    },
    {
      type: "Professional",
      price: 32,
      ideal: "Everything a growing independent business needs to thrive.",
      features: [
        "Everything in Starter, plus:",
        "Custom Branding",
        "Workflow Automations",
        "Client Portal",
        "Unlimited Scheduling events",
        "QuickBooks Integration",
        "Calendly Integration",
        "Zapier Integration",
        "Up to 15 Project Collaborators",
      ],
    },
    {
      type: "Business",
      price: 52,
      ideal: "The perfect package for small businesses and agencies.",
      features: [
        "Everything in Professinal, plus:",
        "Subcontractor Management",
        "Hiring Agreement Templates(1099 contractors)",
        "Subcontractor Onboarding",
        "Talent Pool",
        "3 Team Seats additional seats $9/month",
        "Accountant Access",
        "Connect Multiple Bank Accounts",
        "Unlimited Subcontractors",
        "Unlimited Project Collaborators",
      ],
    },
  ],
};

export default plans;
